version: '3'

services:
  db:
    build: ./docker/db/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: local_db
      MYSQL_USER: local_db
      MYSQL_PASSWORD: 123456
    volumes:
      - ./volumes/db:/var/lib/mysql
    restart: always

  web:
    build: ./docker/web/7.4
    volumes:
      - ./web/:/var/www/html/
    working_dir: /var/www/html/
    depends_on:
      - db
    links:
      - db
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./web/:/var/www/html
    ports:
      - 8080:80
    links:
      - web
    environment:
      - NGINX_HOST=localpontyk
      - NGINX_PORT=80

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8081:8080

  pma:
   image: phpmyadmin/phpmyadmin
   restart: always
   links:
     - mysql:db
   ports:
     - 8082:80
   environment:
     MYSQL_ROOT_PASSWORD: 123456