version: '3'

services:
  db:
    build: ./docker/configs/db/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: local_db
      MYSQL_USER: local_db
      MYSQL_PASSWORD: 123456
    volumes:
      - ./docker/volumes/db:/var/lib/mysql
    # restart: always
    container_name: proj-db
    networks:
      - proj-network


  php:
    build: ./docker/configs/php/7.4-fpm
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html/
    depends_on:
      - db
    links:
      - db
    container_name: proj-php
    networks:
      - proj-network

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/configs/nginx:/etc/nginx/conf.d
      - ./:/var/www/html
    ports:
      - 8080:80
    links:
      - php
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    container_name: proj-nginx
    networks:
      - proj-network

  pma:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    container_name: proj-pma
    networks:
      - proj-network

networks:
  proj-network:
    driver: bridge
